spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/your_database_name?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: redis-server
      port: 6379
      password: your_redis_password

server:
  port: 8080 # 애플리케이션이 실행될 포트 번호

logging:
  level:
    org:
      springframework: INFO # Spring 관련 로깅 수준 설정

